## MT09 - TP2 - Automne 2024
### Elimination de Gauss et factorisation LU

1. Ecrire une fonction python 
```
x = solsup(U,b)
```
qui, étant donné $U$ une matrice triangulaire supérieure de taille $n\times n$ et $b$ vecteur colonne de taille $n$, calcule $x$ solution de $Ux=b$.

Application : utiliser la fonction `solsup()` pour déterminer la solution de 

$$
\begin{pmatrix} 1 & 2 & 3 \\ 0 & 4 & 8 \\ 0 & 0 & 5 \end{pmatrix} x = \begin{pmatrix} 6 \\ 16 \\ 15 \end{pmatrix}.
$$

In [60]:
import numpy as np
import numpy.linalg as la
# import matplotlib.pyplot as plt

def solsup(U, b):
    """ Résolution du système triangulaire supérieur Ux=b """
    n = np.size(b)
    x = np.zeros(n)
    # VOIR POLY
    # A COMPLETER ...
    a=b*1
    x[n-1]=b[n-1]/U[n-1,n-1]
    for i in range(n-2,-1,-1):
        for j in range(i+1,n):
            a[i]-=x[j]*U[i,j]
        x[i]=a[i]/U[i,i]

    return x
    #fini
U = np.array([[1, 2, 3], [0, 4, 8], [0, 0, 5]], dtype=np.float64);
b = np.array([6, 16, 15], dtype=np.float64);
x = solsup(U, b);
print('x = ', x)
# Verification
print('Ux = ', U@x, '\nb = ', b)
print('Ux-b = ', U@x - b)

x =  [ 1. -2.  3.]
Ux =  [ 6. 16. 15.] 
b =  [ 6. 16. 15.]
Ux-b =  [0. 0. 0.]


2. Ecrire une fonction python
```
U, e = trisup(A,b)
```
qui, étant donné $A$ matrice carrée de taille $n\times n$ et $b$ vecteur colonne de taille $n$, déterminer par la méthode d'élimination de Gauss, quand c'est possible, la matrice $U$ triangulaire supérieure et le vecteur colonne $e$ tel que $Ax=b$
$\Leftrightarrow$ $Ux = e$.

On rappelle l'algorithme d'élimination de Gauss:

### Algorithme de Gauss

In [61]:
def trisup(A, b):
# Méthode d'elimination de Gauss
    Am = np.copy(A)
    bm = np.copy(b) 
    n = np.size(b)
    for k in np.arange(0,n):
        if np.abs(Am[k,k]) < 1e-15:
            raise SystemExit("ERREUR : Pivot nul, k=", k, '\n')
        # VOIR COURS
        # A COMPLETER
        for i in range(k+1,n):
            bm[i]-=Am[i,k]/Am[k,k]*bm[k]
            Am[i,]-=Am[i,k]/Am[k,k]*Am[k,]
        #fini
    if np.abs(Am[n-1,n-1]) < 1e-15:
        raise SystemExit("ERREUR : Pivot A_nn nul\n");
    return Am, bm

Application : utiliser la fonction `trisup()` pour déterminer un système d'équations équivalent au système

$$
\begin{pmatrix} 3 & 1 & 2 \\ 3 & 2 & 6 \\ 6 & 1 & -1 \end{pmatrix} x = \begin{pmatrix} 2 \\ 1 \\ 4 \end{pmatrix}.
$$

In [62]:
A=np.array([[3,1,2],[3,2,6],[6,1,-1]],dtype=np.float64);
b=np.array([2,1,4])
U,e=trisup(A, b)
print('U = ', U)
print('e = ', e)


U =  [[ 3.  1.  2.]
 [ 0.  1.  4.]
 [ 0.  0. -1.]]
e =  [ 2 -1 -1]


3. Ecrire une fonction 
```
x = resolG(A, b)
```
qui, étant donné $A$ matrice carrée de taille $n\times n$ et $b$ vecteur colonne de taille $n$, calcule et retourne 
(quand c'est possible) la solution de $Ax=b$ en utilisant la méthode d'élimination de Gauss. Cette fonction doit
utiliser les 2 fonctions précédentes.

In [63]:
def resolG(A,b):
    # A COMPLETER
    U,e=trisup(A,b)
    x=solsup(U,e)
    #fini
    return x;

Application : utiliser la fonction `resolG()`pour déterminer la solution de

$$
\begin{pmatrix} 1 & 2 & 3 \\ 5 & 2 & 1 \\ 3 & -1 & 1 \end{pmatrix} x = \begin{pmatrix} 5 \\ 5 \\ 6 \end{pmatrix},
\quad \text{puis}\quad
\begin{pmatrix} 2 & 1 & 5 \\ 1 & 2 & 4 \\ 3 & 4 & 10 \end{pmatrix} x = \begin{pmatrix} 5 \\ 5 \\ 6 \end{pmatrix}.
$$

In [64]:
x1=resolG(np.array([[1,2,3],[5,2,1],[3,-1,1]],dtype=np.float64),np.array([5,5,6]));
print('x1 = ', x1)

x1 =  [ 0.         -0.75        1.88235294]


In [65]:
# x2=resolG(np.array([[2,1,5],[1,2,4],[3,4,10]],dtype=np.float64),np.array([5,5,6]));
# print('x2 = ', x2)
# pas possible de GS

4. Ecrire une fonction
```
L, U = LU(A)
```
qui, étant donné $A$ de taille $n\times n$, détermine une matrice triangulaire supérieure $U$ et une matrice 
triangulaire inférieure $L$ vérifiant $A=LU$.

NB : on poura en particulier reprendre la fonction `trisup()` que l''on modifiera pour obtenir la fonction `LU()`.

In [66]:
def LU(A):
    U = np.copy(A)
    n = np.size(A[0,:])
    L = np.eye(n, dtype=np.float64)
    for k in np.arange(0,n):
        if np.abs(U[k,k])<1e-15:
            raise SystemExit("Pivot nul\n")
        # A COMPLETER

        for i in range(k+1,n):
            L[i,k]=U[i,k]/U[k,k]
            U[i,]-=U[i,k]/U[k,k]*U[k,]

        #fini
    if np.abs(U[n-1,n-1])<1e-15:
        raise SystemExit("Pivot A_nn nul\n")
    return L, U

Application : utiliser la fonction `LU()` pour déterminer $L$ et $U$ dans le cas où

$$
A = \begin{pmatrix} 3 & 1 & 2 \\ 3 & 2 & 6 \\ 6 & 1 & -1 \end{pmatrix}.
$$

In [67]:
A = np.array([[3, 1, 2], [3, 2, 6], [6, 1, -1]], dtype=np.float64);
L, U = LU(A);
print(L, U, A-L@U)

[[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 2. -1.  1.]] [[ 3.  1.  2.]
 [ 0.  1.  4.]
 [ 0.  0. -1.]] [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


5. Ecrire une fonction 
```
x = solinf(L,b)
```
qui, étant donné $L$ matrice triangulaire inférieure de taille $n\times n$ et $b$ vecteur colonne de taille $n$, calcule $x$ solution de $Lx=b$

In [68]:
def solinf(L, b):
    # A COMPLETER
    n = np.size(b)
    x = np.zeros(n)
    a=b*1
    x[0]=b[0]/L[0,0]
    for i in range(1,n):
        for j in range(0,i):
            a[i]-=x[j]*L[i,j]
        x[i]=a[i]/L[i,i]
    #fini
    return x

Application : utiliser la fonction `solinf()` pour déterminer la solution de

$$
\begin{pmatrix} 1 & 0 & 0 \\ 2 & 3 & 0 \\ 1 & 4 & -1 \end{pmatrix} x = \begin{pmatrix} 1 \\ 8 \\ 10 \end{pmatrix}.
$$

In [69]:
x=solinf(np.array([[1,0,0],[2,3,0],[1,4,-1]],dtype=np.float64),np.array([1,8,10]))
print('x = ', x)

x =  [ 1.  2. -1.]


6. Ecrire une fonction 
```
x = resolLU(A,b)
```
qui calcule, quand c'est possible, la solution de $Ax=b$ en utilisant la factorisation $A=LU$.

In [70]:
def resolLU(A, b):
    # A COMPLETER
    L, U = LU(A)
    Y=solinf(L, b)
    x=solsup(U,Y)
    #fini
    return x;

Application : utiliser la fonction `resolLU()` pour déterminer la solution de

$$
\begin{pmatrix} 1 & 2 & 3 \\ 5 & 2 & 1 \\ 3 & -1 & 1 \end{pmatrix} x = \begin{pmatrix} 5 \\ 5 \\ 6 \end{pmatrix}.
$$

In [71]:
x=resolLU(np.array([[1,2,3],[5,2,1],[3,-1,1]],dtype=np.float64),np.array([5,5,6],dtype=np.float64));
print(np.array([[1,2,3],[5,2,1],[3,-1,1]])@x)
print('x = ', x)

[5. 5. 6.]
x =  [ 1. -1.  2.]


7. Ecrire une fonction
```
B = inverse(A)
```
qui calcule la matrice $B$ inverse de $A$ en utilisant `LU()`, `solinf()` et `solsup()` et en minimisant le 
nombre d'opérations.

In [72]:
def inverse(A):
    n = np.size(A[0,:])
    # A COMPLETER
    b=np.eye(n)
    Y=np.zeros((n,n))
    B=np.zeros((n,n))
    L,U=LU(A)
    for i in range(0,n):
        Y[:,i]=solinf(L,b[:,i])
        B[:,i]=solsup(U,Y[:,i])
    #fini
    return B

Application : utiliser la fonction `inverse()` pour déterminer la matrice $B$ inverse de

$$
A = \begin{pmatrix} 1 & 2 & 3 \\ 5 & 2 & 1 \\ 3 & -1 & 1 \end{pmatrix}.
$$

In [76]:
A = np.array([[1, 2, 3], [5, 2, 1], [3, -1, 1]], dtype=np.float64);
B = inverse(A);
C = B@A;
print( B,"\n", C, la.norm(C - np.eye(3)) )

[[-0.08823529  0.14705882  0.11764706]
 [ 0.05882353  0.23529412 -0.41176471]
 [ 0.32352941 -0.20588235  0.23529412]] 
 [[ 1.00000000e+00 -2.22044605e-16 -3.33066907e-16]
 [ 1.11022302e-16  1.00000000e+00  5.55111512e-17]
 [ 5.55111512e-17  5.55111512e-17  1.00000000e+00]] 4.80740671595891e-16
